version: '3.9'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=username
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - /data/rabbitmq:/var/lib/rabbitmq:rw
    restart: unless-stopped
    mem_limit: 2g
    cpu_shares: 768
    ports:
      - 5672:5672
      - 15672:15672